language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/thingsboard
#
install:
    - pip install -U platformio
    - platformio update
#
script:
    - platformio ci --lib="InfiniSolarP18" --project-conf="platformio.ini"
